### PR TITLE
Clean up Dockerfile and move it into 4.1 directory

### PR DESCRIPTION
**Pull request by teohhanhui**
Notable changes:
- Removed `ONBUILD`. Use volume bind-mount instead, or `COPY` in project Dockerfile.
- Changed Varnish port to 6081. Host port is configurable so this should not be an issue. Removed useless `VARNISH_PORT` environment variable.
- Added `VARNISHD_PARAMS` and `VCL_CONFIG` environment variables. Now we have feature parity with `million12/varnish`.
- Changed Varnish user (`varnishd` -> `varnish`) to follow the default (and the norm of distro packages).

### CODE REVIEW

**Comment by Plopix** [comment]
+1

**Comment by teohhanhui** [comment]
Since there is no response from the project maintainer(s), we're just going to maintain our own fork: https://github.com/tripviss/docker-varnish

**Comment by teohhanhui** [comment]
What do you think about this, @albertsun?

**Comment by teohhanhui** [comment]
Especially relevant with Varnish 5.0 just released.

**Comment by albertsun** [comment]
Hi, we haven't had time to review this - and this project is not very well maintained at the moment (as you've noticed I'm sure). I'd encourage you to keep maintaining and using your fork.

We still need the `VARNISH_PORT` variable since these containers could be run in a system that doesn't allow the configuration of a host port — for instance when running them as  part of a kubernetes pod with multiple containers.

**Pull request closed without merging**
